[workspace]
members = [
  "kernel-5.4.87",
  "kernel-5.4.119",
  "release",
  "growpart",
  "libstd-rust",
  "ca-certificates",
  "eklet-agent",
  "containerd",
  "runc",
  "cni-plugins",
  "eklet-agent-net",
  "ebpf-tools",
  "eks-tool",
  "cosfs",
  "nvidia",
  "aegis",
]

[profile.dev]
debug = false
opt-level = 'z'

[profile.dev.build-override]
opt-level = 'z'
