[package]
name = "containerd"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[build-dependencies]
runc = {path = "../runc"}
cni-plugins = { path = "../cni-plugins" }
